# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module FouleFactoryApi
  class TemplateInstructionWriterServiceModel < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :instruction

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :order

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["instruction"] = "Instruction"
        @hash["order"] = "Order"
      end
      @hash
    end

    def initialize(instruction = nil,
                   order = nil)
      @instruction = instruction
      @order = order
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        instruction = hash["Instruction"]
        order = hash["Order"]

        # Create object from extracted values
        TemplateInstructionWriterServiceModel.new(instruction,
                                                  order)
      end
    end
  end
end
