# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module FouleFactoryApi
  class TemplateColumnWriterServiceModel < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id_template_column_type

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :column

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :order

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["id_template_column_type"] = "IdTemplateColumnType"
        @hash["column"] = "Column"
        @hash["order"] = "Order"
      end
      @hash
    end

    def initialize(id_template_column_type = nil,
                   column = nil,
                   order = nil)
      @id_template_column_type = id_template_column_type
      @column = column
      @order = order
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        id_template_column_type = hash["IdTemplateColumnType"]
        column = hash["Column"]
        order = hash["Order"]

        # Create object from extracted values
        TemplateColumnWriterServiceModel.new(id_template_column_type,
                                             column,
                                             order)
      end
    end
  end
end
