# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module FouleFactoryApi
  class TemplateQuestionWriterServiceModel < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :require

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id_template_object_question_type

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :order

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :option

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :choices

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["title"] = "Title"
        @hash["require"] = "Require"
        @hash["id_template_object_question_type"] = "IdTemplateObjectQuestionType"
        @hash["order"] = "Order"
        @hash["option"] = "Option"
        @hash["choices"] = "Choices"
      end
      @hash
    end

    def initialize(title = nil,
                   require = nil,
                   id_template_object_question_type = nil,
                   order = nil,
                   option = nil,
                   choices = nil)
      @title = title
      @require = require
      @id_template_object_question_type = id_template_object_question_type
      @order = order
      @option = option
      @choices = choices
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        title = hash["Title"]
        require = hash["Require"]
        id_template_object_question_type = hash["IdTemplateObjectQuestionType"]
        order = hash["Order"]
        option = hash["Option"]
        choices = hash["Choices"]

        # Create object from extracted values
        TemplateQuestionWriterServiceModel.new(title,
                                               require,
                                               id_template_object_question_type,
                                               order,
                                               option,
                                               choices)
      end
    end
  end
end
