# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module FouleFactoryApi
  class FouleFactoryApiClient
    # Singleton access to task_answer_texts controller
    # @return [TaskAnswerTextsController] Returns the controller instance
    def task_answer_texts
      TaskAnswerTextsController.instance
    end

    # Singleton access to task_answer_choices controller
    # @return [TaskAnswerChoicesController] Returns the controller instance
    def task_answer_choices
      TaskAnswerChoicesController.instance
    end

    # Singleton access to projects controller
    # @return [ProjectsController] Returns the controller instance
    def projects
      ProjectsController.instance
    end

    # Singleton access to csv_files controller
    # @return [CsvFilesController] Returns the controller instance
    def csv_files
      CsvFilesController.instance
    end

    # Singleton access to account controller
    # @return [AccountController] Returns the controller instance
    def account
      AccountController.instance
    end

    # Singleton access to templates controller
    # @return [TemplatesController] Returns the controller instance
    def templates
      TemplatesController.instance
    end

    # Singleton access to tasks controller
    # @return [TasksController] Returns the controller instance
    def tasks
      TasksController.instance
    end

    # Singleton access to task_lines controller
    # @return [TaskLinesController] Returns the controller instance
    def task_lines
      TaskLinesController.instance
    end

    # Initializer with authentication and configuration parameters
    def initialize(basic_auth_user_name: nil, basic_auth_password: nil)
      Configuration.basic_auth_user_name = basic_auth_user_name
      Configuration.basic_auth_password = basic_auth_password
    end
  end
end
